from pathlib import Path
import requests
from feedgen.feed import FeedGenerator

HEADERS = {
    "X-Frontend-Id": "6",
    "X-Frontend-Version": "0",
    "X-Niconico-Language": "ja-jp",
    "User-Agent": "nico-rss-feedly/1.0",
}

BASE_URL = "https://nvapi.nicovideo.jp/v3/users/{}/videos?sortKey=registeredAt&sortOrder=desc&pageSize=50&page=1"
RSS_DIR = Path("rss")
RSS_DIR.mkdir(exist_ok=True)


def load_users():
    with open("users.txt", encoding="utf-8") as f:
        return [x.strip() for x in f if x.strip()]


def fetch(user_id):
    url = BASE_URL.format(user_id)
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()["data"]["items"]


def make_feed(user_id, items):
    fg = FeedGenerator()

    fg.id(f"nico-user-{user_id}")
    fg.title(f"Niconico User {user_id}")
    fg.link(href=f"https://www.nicovideo.jp/user/{user_id}/video")
    fg.description("Generated by GitHub Actions")

    for item in items:
        e = fg.add_entry()

        v = item["essential"]

        video_id = v["id"]

        e.id(video_id)
        e.title(v["title"])

        e.link(
            href=f"https://www.nicovideo.jp/watch/{video_id}"
        )

        thumb = (
            v.get("thumbnail", {}).get("largeUrl")
            or v.get("thumbnail", {}).get("middleUrl")
            or v.get("thumbnail", {}).get("url")
            or ""
        )

        description = f"""
<img src="{thumb}"><br><br>
{v["shortDescription"]}
"""
        e.description(description)
        e.pubDate(v["registeredAt"])
    fg.rss_file(str(RSS_DIR / f"{user_id}.xml"))





def make_all_feed(items):

    items.sort(
        key=lambda x: x["essential"]["registeredAt"],
        reverse=True
    )

    fg = FeedGenerator()

    fg.id("nico-all")
    fg.title("Niconico All")
    fg.link(href="https://www.nicovideo.jp/")
    fg.description("Generated by GitHub Actions")

    for item in items[:50]:

        v = item["essential"]

        e = fg.add_entry()

        e.id(v["id"])

        e.title(v["title"])

        e.link(
            href=f"https://www.nicovideo.jp/watch/{v['id']}"
        )

        thumb = (
            v.get("thumbnail", {}).get("largeUrl")
            or v.get("thumbnail", {}).get("middleUrl")
            or v.get("thumbnail", {}).get("url")
            or ""
        )

        description = f"""
<img src="{thumb}"><br><br>
{v["shortDescription"]}
"""

        e.description(description)

        e.pubDate(v["registeredAt"])

    fg.rss_file(str(RSS_DIR / "all.xml"))






def main():
    users = load_users()

    all_items = []

    for user in users:
        print("Processing", user)
        items = fetch(user)
        make_feed(user, items)
        all_items.extend(items)
    make_all_feed(all_items)


if __name__ == "__main__":
    main()
